apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "block-indexer.fullname" . }}-api
  labels: {{ include "block-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: {{ include "block-indexer.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "block-indexer.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}/api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 9101
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: block-indexer-secrets
                  key: POSTGRES_URL
          resources: {{ toYaml .Values.resources.api | nindent 12 }}
