apiVersion: v1
kind: Service
metadata:
  name: {{ include "block-indexer.fullname" . }}-api
  labels: {{ include "block-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "block-indexer.fullname" . }}-api
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: 8080
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 9101
