version: '3'

services:
  postgres:
    image: postgres:16
    container_name: explorer-postgres
    environment:
      POSTGRES_USER: explorer
      POSTGRES_PASSWORD: explorer_pass
      POSTGRES_DB: explorer_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U explorer -d explorer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# volumes:
