apiVersion: v1
kind: Secret
metadata:
  name: block-indexer-secrets
type: Opaque
stringData:
  POSTGRES_URL: postgres://user:pass@postgres:5432/block_indexer?sslmode=disable
  REDIS_ADDR: redis:6379
  REDIS_PASSWORD: ""
